"use client";

import { Check, Clock3, LoaderCircle, MapPin, PackageCheck, Phone, Store, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { MapClient } from "@/components/maps/map-client";
import type { MapPoint } from "@/components/maps/osm-map";
import type { TrackingSnapshot } from "@/lib/contracts";

const orderSteps=["PLACED","CONFIRMED","PACKING","READY","OUT_FOR_DELIVERY","DELIVERED"];
export function TrackingView({trackingCode}:{trackingCode:string}){const [data,setData]=useState<TrackingSnapshot|null>(null);const [error,setError]=useState("");
  useEffect(()=>{let active=true;async function load(){const response=await fetch(`/api/orders/${encodeURIComponent(trackingCode)}/tracking`,{cache:"no-store"});const payload=await response.json();if(!active)return;if(response.ok){setData(payload.data);setError("")}else setError(payload.error??"Tracking unavailable")};load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer)}},[trackingCode]);
  if(error)return <div className="rounded-2xl border border-[#e1e8e0] bg-white p-8 text-center"><PackageCheck className="mx-auto"/><h2 className="mt-4 text-xl font-black">{error}</h2></div>;
  if(!data)return <div className="grid min-h-[420px] place-items-center"><LoaderCircle className="animate-spin"/></div>;
  const points: MapPoint[]=[];if(data.delivery){points.push({id:"store",position:data.delivery.store,label:process.env.NEXT_PUBLIC_STORE_NAME??"UK Store",kind:"store"});if(data.delivery.destination)points.push({id:"customer",position:data.delivery.destination,label:"Delivery destination",kind:"customer"});if(data.delivery.current)points.push({id:"driver",position:data.delivery.current,label:data.delivery.driverName??"Delivery partner",detail:data.delivery.lastLocationAt?`Updated ${new Date(data.delivery.lastLocationAt).toLocaleTimeString()}`:undefined,kind:"driver"})}
  const currentIndex=orderSteps.indexOf(data.order.status);
  return <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div><MapClient points={points} path={data.path}/><div className="mt-3 flex items-center gap-2 rounded-2xl border border-[#e1e8e0] bg-white p-4 text-xs text-[#74736c]"><Clock3 size={16}/>{data.delivery?.lastLocationAt?`Location updated ${new Date(data.delivery.lastLocationAt).toLocaleString()}`:"Waiting for the delivery partner to share location."}</div></div><section className="rounded-2xl border border-[#e1e8e0] bg-white p-6"><p className="text-xs font-black uppercase tracking-[.15em] text-[#6f7d71]">Order status</p><h2 className="mt-2 text-2xl font-black">{data.order.status.replaceAll("_"," ")}</h2>{data.delivery?.driverName&&<div className="mt-5 flex items-center gap-3 rounded-2xl bg-[#f1f7f0] p-4"><span className="grid size-11 place-items-center rounded-lg bg-[#079a31] text-white"><Truck size={18}/></span><div className="flex-1"><strong className="block text-sm">{data.delivery.driverName}</strong><span className="text-xs text-[#85847d]">Delivery partner</span></div>{data.delivery.driverPhone&&<a href={`tel:${data.delivery.driverPhone}`} className="grid size-10 place-items-center rounded-lg bg-white"><Phone size={16}/></a>}</div>}<div className="mt-7 space-y-5">{[{key:"PLACED",title:"Order placed",icon:Check},{key:"PACKING",title:"Packed at store",icon:Store},{key:"OUT_FOR_DELIVERY",title:"Out for delivery",icon:Truck},{key:"DELIVERED",title:"Delivered",icon:PackageCheck}].map(step=>{const index=orderSteps.indexOf(step.key);const done=currentIndex>=index;return <div key={step.key} className="flex gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-full ${done?"bg-[#079a31] text-white":"bg-[#f1f7f0] text-[#6f7d71]"}`}><step.icon size={16}/></span><div><strong className="block text-sm">{step.title}</strong><span className="text-xs text-[#858d86]">{done?"Completed or in progress":"Pending"}</span></div></div>})}</div><div className="mt-7 rounded-2xl border border-[#e1e8e0] p-4"><div className="flex items-start gap-3"><MapPin size={17}/><div><strong className="block text-sm">Destination</strong><span className="text-xs text-[#7d857e]">{data.order.city}</span></div></div>{data.order.estimatedArrival&&<p className="mt-4 text-xs font-bold">ETA: {new Date(data.order.estimatedArrival).toLocaleString()}</p>}</div></section></div>
}
